<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MessageFlowExplorer.Analyzer\MessageFlowExplorer.Analyzer.csproj" />
    <ProjectReference Include="..\MessageFlowExplorer.Core\MessageFlowExplorer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\web\dist\**\*.*" LinkBase="wwwroot" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>mfe</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
